name = "podcast-shadow-reader"
pages_build_output_dir = "./dist"
compatibility_date = "2026-06-05"

[[d1_databases]]
binding = "DB"
database_name = "shadowcast"
database_id = "9a8c32dc-aa0a-4cd8-8198-83144cb60a59"
preview_database_id = "DB"
migrations_dir = "./migrations"
